trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    sudo apt-get update
    sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get install docker-ce
  displayName: 'Install Docker'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: 'Docker-Compose-Template/docker-compose-default.yml'
    dockerComposeFileArgs: |
      CONFIG_PATH=https://github.com/Azure/azure-event-hubs-emulator-installer/blob/main/EventHub-Emulator/Config/Config.json
      ACCEPT_EULA=Y
    projectName: 'microsoft-azure-eventhubs'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d'
