

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # Docker
    - task: DockerCompose@0
      inputs: 
        containerregistrytype: 'Container Registry'
        dockerComposeFile: 'Docker-Compose-Template/docker-compose-default.yml'
        action: 'Run a Docker Compose command'
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
