trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    sudo apt-get update
    sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get install docker-ce
  displayName: 'Install Docker'

- script: |
    curl -L https://raw.githubusercontent.com/Saglodha/azure-event-hubs-emulator-installer/main/docker-pipeline.yml -o docker-compose-default-saglodha-1.yml
  displayName: 'Download Docker Compose file'

- script: |
    curl -L https://github.com/Azure/azure-event-hubs-emulator-installer/blob/main/EventHub-Emulator/Config/Config.json -o Config.json
  displayName: 'Download Config file'


- script: |
    echo "##vso[task.setvariable variable=CONFIG_PATH;]$(System.DefaultWorkingDirectory)/Config.json"
    echo "##vso[task.setvariable variable=ACCEPT_EULA;]Y"
  displayName: 'Set Variables'


- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose-default-saglodha-1.yml'
    projectName: 'microsoft-azure-eventhubs'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'docker compose -f docker-compose-default.yml up -d'